services:
  - type: web
    name: cocots-sports-api
    env: python
    rootDir: ml-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ALLOWED_ORIGINS
        sync: false
      - key: NBA_API_KEY
        sync: false
